### ISSUE TITLE
config.Config() doesn't create a .giraffepg if it doesn't exist, contrary to documentation

### ISSUE THREAD

**Issue by del82** [capitalone/giraffez#11]
The documentation for config.Config says that Config() "[Creates an encryption key at ~/.giraffepg if one does not exist](https://github.com/capitalone/giraffez/blob/ee5e27f9e8bb9a3003371d0385fb88aabdbd97a3/giraffez/config.py#L100)"

But it doesn't, instead raising a `KeyNotFound` error:

```
In [1]: import giraffez.config

In [2]: cfg = giraffez.config.Config(mode='w')

---------------------------------------------------------------------------
KeyNotFound                               Traceback (most recent call last)
<ipython-input-2-27c6bd581e19> in <module>()
----> 1 cfg = giraffez.config.Config(mode='w')

/opt/anaconda/lib/python3.5/site-packages/giraffez/config.py in __init__(self, conf, mode, key_file)
    127         if key_file is None:
    128             self._key_file = home_file(".giraffepg")
--> 129         self._key_file = _get_key_file(key_file)
    130         self.mode = mode
    131         _check_file_permissions(self._config_file, 0o600)

/opt/anaconda/lib/python3.5/site-packages/giraffez/config.py in _get_key_file(key_file)
     62         key_file = os.path.abspath(key_file)
     63     if not file_exists(key_file):
---> 64         raise KeyNotFound("Key file is required to use giraffez config.")
     65     return key_file
     66

KeyNotFound: Key file is required to use giraffez config.
```

This is either a bug in the code or a bug in the docs, and I'd advocate for it being a bug in the code.  It would be great if it were possible to use this `config` API to create an initial configuration for a new user, which would require the ability to construct a Config object without a pre-existing `.giraffepg`, maybe with the option to create one as part of the constructor.

**Comment by del82** [comment]
It looks like the only way to generate a `.giraffepg` file is to run `giraffe config --init`, but if you don't let it clobber your `.girafferc` it won't write a `.giraffepg` either.

So if I'm adding a user to a system and have some useful defaults in `/etc/skel/.girafferc`, those useful defaults get clobbered in order to generate a `.giraffepg`.

**Comment by ChrisRx** [comment]
It is indeed not doing what the docstring says when using `giraffez.config.Config` directly.  It creates that when using the command-line tool by handling those errors in `giraffez/core.py` and providing console prompts.  Originally, `giraffez.config.Config` did lazily create the config and/or key file when not present on the system but was removed because it was implemented in a convoluted way at the time to make it work consistently with both the command-line tool and API (and the docs were not updated to reflect this).

I think there is some room for improvement here for sure, but wanted to respond and go ahead and mention that you can create the key file individually through the API fairly easily with something like:

```Python
from giraffez.encrypt import create_key_file

create_key_file("path/keyfile.txt")
``` 

At a minimum the old docstring needs to be changed and this snippet above added to the usage in the current docs.
