### ISSUE TITLE
`load` fails when delimiter occurs in quoted field

### ISSUE THREAD

**Issue by del82** [capitalone/giraffez#14]
`load` detects the delimiter in the source file, but fails on rows that contain the delimiter in a quoted field.  

For example, for the following source file:

```
one|two|three
four|five|six
seven|"eight|nine"|ten
```
```
$ giraffe load testfile.txt test_container.test_table
ERROR:root:Mismatch length for row
       	['seven', '"eight', 'nine"', 'ten']
       	['one', 'two', 'three']
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/giraffe/command.py", line 376, in insert
    raise FormatError("Mismatch length for row\n\t{0}\n\t{1}".format(row, fields))
FormatError: Mismatch length for row
       	['seven', '"eight', 'nine"', 'ten']
       	['one', 'two', 'three']
Results
 ---> Rows successful: 1
 ---> Rows unsuccessful: 1
 ---> Total: 2
==========================
run took 4.9091s to finish
```

Expected results:  delimiter is ignored within quotes, and load of `seven|"eight|nine"|ten` succeeds with "eight|nine" as a single field.

Actual results:  load of `seven|"eight|nine"|ten` fails.

**Comment by ChrisRx** [comment]
The parsing behavior here is intentionally simple and consistent rather than trying to handle more complex row formats.  The reason for this is that if needing anything more specific, rather than trying to make that part of the parsing performed automatically by the command-line tool, that it would be easier to use the Python API for any formats beyond just the simple delimited ones.  For example, you would be able to use something like the Python standard libraries [csv](https://docs.python.org/3/library/csv.html#csv.reader) to easily read in the file and then use `giraffe.Load` in the Python API (I believe I can whip up a working example if you think that might provide benefit).  Although, with that said maybe we should be using the csv module as the default reader after the delimiter is inferred.   This would probably the more advanced and consistent parsing, be little effort, and may be able to be added without adding too much complexity to the command-line tool usage.  Thoughts?

Another potentially good improvement is JSON, which would also be very easy to configure (easy to infer).  I think this addition would be very useful for both `load` and `mload`.

**Comment by del82** [comment]
Appreciate the desire for simplicity, and also that it's possible to read csvs by using the Python API combined with the `csv` module.  I do think, though, that incorporating full-fledged csv parsing (rather than `"string".split(delimiter)`) into the command-line interface would be a high-value, fairly low-effort addition--  Happy to take this on.

I'm also in agreement about JSON, which is also high-value and fairly low-effort.  

Branch from master or 1.0.6?

**Comment by ChrisRx** [comment]
Yeah, I would branch from 1.1.0 (I just renamed 1.0.6 to that).  The thought is this will require extending the API so a minor version increment is necessary.  The extension will be adding additional keyword parameters to the `from_file` methods on both `giraffez.Load` and `giraffez.MLoad`.

Here is a high-level list of what would be needed:

* Add keywords parameters to Load and MLoad for quotechar
* Add command-line option to specify quotechar
* Update docstrings for new parameter and update `docs/source/command-line.rst`
* Add test for Load and MLoad with new parameter (MLoad might be better tested through the encoder function directly `text_to_strings`)
* Not sure how to best implement the test for JSON data but it should probably do so before any other tests and do so by taking the first line and running it through `json.loads` with a try except

This is just an initial brain dump so this might be different at the time of writing or might need to go a different direction to implement some of the proposed functionality.

 Let me know if you have issues using the 1.1.0 branch, it isn't really any new functionality, but is moving around and consolidating a lot of the C/C++ components so there may be some rough edges on it (still currently testing it).
