### ISSUE TITLE
Add support for BTEQ Syntax

### ISSUE THREAD

**Issue by flolas** [capitalone/giraffez#32]
Hi,

This is a good project, currently in my job I'm working with Teradata and python. It would be great if we can use`giraffez bteq interactive`and `giraffez bteq <bteq file> <querybands>`.

**Comment by ktravis** [comment]
Hi Felipe, thanks for your interest in giraffez, I'm glad you like it! Our goal has not been to emulate existing tools, but instead to provide a natural and user-friendly way to interact with Teradata.

For the interactive shell I would suggest checking out [giraffez shell](http://www.capitalone.io/giraffez/command-line.html#shell). As for taking a BTEQ script as input, from my understanding the commands and syntax involved (outside of actual Teradata SQL) are a facility of BTEQ, not something recognized by the Teradata drivers or server(s) directly. Is there a specific feature of BTEQ that you are missing when using giraffez?

**Comment by ChrisRx** [comment]
As indicated by @ktravis giraffez has the implied bteq functionality in the form of `giraffez shell` and `giraffez cmd <filename>`, so I'm closing this as presumably it was answered and inactivity.  @flolas if you have some features that prompting make the issue that you want to provide later we can address, otherwise I will assume that your question was answered.
