### ISSUE TITLE
Loading Pandas Data to Teradata Problems

### ISSUE THREAD

**Issue by Protesuiq** [capitalone/giraffez#35]
I am experiencing problem loading Pandas dataframe to Teradata via MLOAD. First I got NULL values error as len() of NULL  returns an error. I dropped all rows with null values but still, no luck. Now I have _Teradata PT request failed with code '2583'_.

This is my code:

```
with giraffez.MLoad("DBC.TestTable") as mload:
    mload.columns = df.columns.tolist()
    rows = list(zip(*[df[i].values.tolist() for i in df]))
    for row in rows:
       mload.load_row(row)
    exit_code = mload.finish()
    print("finished load with code {0}".format(exit_code))
    if exit_code == 0:
       mload.cleanup()

```
Is there a better and working way  to mload Pandas DataFrame to Teradata? 

Tools:
Python Version: 3.6
Teradata CLIv2 16.10.0.2
Windows 7

**Comment by ChrisRx** [comment]
I hope I will be able to help, although it is probably not related to Pandas so much as Teradata's mload driver is extremely rigid and difficult to work with (the protocol itself is really limited).  I will need a traceback (preferred) or some additional context on what is meant by NULL values error.  The traceback associated with the 2583 error will also be needed to determine what is happening with the 2583 error.  This is an error that happens anytime the mload driver attempts to restart a job but the work table is missing.  The way giraffez attempts to make the mload more friendly is by disallowing restarts, however, mload is kind of difficult to work with procedurally so it basically needs to attempt to restart, fail, and then release to then "cleanup" the previous unsuccessful job.  This should be handled automatically though, as the giraffez.MLoad class will issue a `release` command for you in the case it receives a 2583.

**Comment by Protesuiq** [comment]
I hope this will give the context:

This is my df before I drop the NA values:
![image](https://user-images.githubusercontent.com/14926709/28857481-1d3b8ec8-774a-11e7-8b02-ebee123cb306.png)

When I attempt to load this. I get:

```
Connection: Connecting to data source 'db1' ...
Connection: Connection to 'db1' established successfully.
MLoad: Requesting column info for table 'DBC.TestTable' ...
MLoad: Initiating Teradata PT request (awaiting server)  ...
MLoad: Teradata PT request accepted.
Connection: Closing Teradata connection ...
MLoad: Closing Teradata PT connection ...
MLoad: Acquisition phase was not called before closing.
MLoad: Ending acquisition phase ...
MLoad: Acquisition phase ended.
MLoad: Teradata PT request complete.
Connection: Connection to 'db1' closed.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-4282e9006bed> in <module>()
      3     rows = list(zip(*[df[i].values.tolist() for i in df]))
      4     for row in rows:
----> 5        mload.load_row(row)
      6     exit_code = mload.finish()
      7     print("finished load with code {0}".format(exit_code))

C:\Users\MYUSERNAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\giraffez\mload.py in load_row(self, items, panic)
    372             self._initiate()
    373         try:
--> 374             data = self.processor(items)
    375             row_status = self.load.put_row(data)
    376             if not self._handle_error(row_status):

C:\Users\MYUSERNAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\giraffez\utils.py in _pipeline(x)
     66 def pipeline(funcs):
     67     def _pipeline(x):
---> 68         return reduce(lambda a, f: f(a), funcs, x)
     69     return _pipeline
     70 

C:\Users\MYUSERNAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\giraffez\utils.py in <lambda>(a, f)
     66 def pipeline(funcs):
     67     def _pipeline(x):
---> 68         return reduce(lambda a, f: f(a), funcs, x)
     69     return _pipeline
     70 

C:\Users\MYUSERNAME\AppData\Local\Continuum\Anaconda3\lib\site-packages\giraffez\encoders.py in _encoder(items)
    278                 data.append(value)
    279             elif column.type in VAR_TYPES:
--> 280                 data.append(struct.pack("H", len(item)) + ensure_bytes(item))
    281             elif column.type in DATE_TYPES:
    282                 date_value = Date.from_string(item)

TypeError: object of type 'float' has no len()

```

That error is reproduced by len(0) or len(np.nan). So not wanting to deal with this now, I created a subset that has drop all na: de = df.dropna(): I then dropped:

```
DROP TABLE DBC.TestTable_e1;
DROP TABLE DBC.TestTable_e2;
DROP TABLE DBC.TestTable_wt;
```

Then I tried to again with de:

```
Connection: Connecting to data source 'db1' ...
Connection: Connection to 'db1' established successfully.
MLoad: Requesting column info for table 'DBC.TestTable' ...
MLoad: Initiating Teradata PT request (awaiting server)  ...
MLoad: Teradata PT request failed with code '2583'.
MLoad: Attempting release for table DBC.TestTable
MLoad: Initiating Teradata PT request (awaiting server)  ...
MLoad: Teradata PT request accepted.
Error Code | Error Description
------------------------------
10517      | None             
MLoad: Ending acquisition phase ...
MLoad: Acquisition phase ended.
MLoad: Beginning apply phase ...
MLoad: Update error row count failed.
MLoad: Apply phase ended.
Connection: Closing Teradata connection ...
MLoad: Closing Teradata PT connection ...
finished load with code 12
MLoad: Teradata PT request complete.
Connection: Connection to 'db1' closed.
```

**Comment by ChrisRx** [comment]
It appears to be resolving the 2583 error correctly and finishing the initiation step.  This is because it starts initiating again after saying "Attempting release ..." and then succeeds with "Teradata PT request accepted."  The part that it appears to be messing up on comes after when it loads the first row attempt.  I'm not 100% but I believe that error code 10517 indicates that it hit the internal error limit of 1.  This is set to 1 so that if there is an unknown error that it will return immediately (the unknown errors shouldn't be happening, because it indicates that the encoder received data that didn't error and what the giraffez encoder produced was incorrect).  

I'm investigating a few things on my side, but while I do that, take a look at the values that are being set from pandas for `mload.columns` and ensure that they represent the column names of the target table and additionally pull a sample row from the dataframe using the same method you are using above and ensure that those values correspond to both the `mload.columns` and the column data type in the target table.  If the columns that are being named are for data types that don't match what was is being sent to Teradata in the target table, it could possibly create this kind of error.

The last thing I had for now was a question around why Pandas is giving a 0 (float type) for the type that is being loaded into a character teradata data type?  Is that how Pandas returns null values rather than using the Python NoneType?  Or is the column that is giving the 0 value not a character type but is attempting to loading into a Teradata table that is defined as a character type (char, varchar, etc)?  Regardless of what this ends up being I believe this is something that can be improved for the user with a better check and/or error message for this kind of thing, but will need to make sure I understand what is happening there first.

**Comment by Protesuiq** [comment]
It was the created table columns arrangement and np.na that were causing. I fixed my writings a normal MLOAD script that took csv generated from df where I replaced np.nan with -9999.

Thank you for your assistance.
