### ISSUE TITLE
Problem with install on Windows

### ISSUE THREAD

**Issue by SimaoRodrigo** [capitalone/giraffez#41]
When I wan't to upgrade giraffez by pip:
pip install --upgrade giraffez

I've got an error:
 c:\temp\pip-build-sjcz246m\giraffez\giraffez\src\common.h(34): fatal error C1083: Couldn't open file: '_strptime.c': No such file or directory.

It is not happening when I clone repo from git.

**Comment by ChrisRx** [comment]
It would appear that because distutils does not detect that the `_strptime.c` is being compiled that it does not include it, and it is the only file with a `.c` extension that isn't being directly compiled (rather it is included in other C files).  The fix here should be pretty easy, just adding it to MANIFEST.in.  Look for a fix soon today in version 2.0.17, as well as, Windows wheels being refreshed so that when you pip install it shouldn't even have to compile it on Windows.

**Comment by SimaoRodrigo** [comment]
Retest ok. 
Thanks a lot.

Cheers
