### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte invalid start byte 

### ISSUE THREAD

**Issue by ausiddiqui** [capitalone/giraffez#50]
my environment version info:
```
giraffez 2.0.19
macOS 10.13.2
python 3.5
Teradata ODBC / TTU 16.10
Teradata Server 15.10
```
When I run this for any number of tables I get the same result. I am able to get a legitimate response when I use `giraffez cmd "select top 1 * from mydb.my_table"` I get the print out to stdout properly.  But `giraffez export` seems to be causing issues, only spits out the column headers:

```bash
myComp:~|⇒  giraffez export "select top 1 * from mydb.my_table"
Connection: Connecting to data source 'data-server' ...
Connection: Connection to 'data-server' established successfully.
Export: Initiating Teradata PT request (awaiting server)  ...
Export: Teradata PT request accepted.
Export: Executing ...
  delimiter => "|"
  null      => "NULL"
  output    => "stdout"
  encoding  => "str"
  query     => "select top 1 * from mydb.my_table"
--------------------------------
version|id|resid|tid|parentid|off|type|prod|status|dtl|flagb|flagd
Connection: Closing Teradata connection ...
Export: Closing Teradata PT connection ...
Export: Teradata PT request complete.
Connection: Connection to 'data-server' closed.
Traceback (most recent call last):
  File "/Users/ash/miniconda3/envs/py35/bin/giraffez", line 11, in <module>
    sys.exit(main())
  File "/Users/ash/miniconda3/envs/py35/lib/python3.5/site-packages/giraffez/__main__.py", line 25, in main
    MainCommand().run()
  File "/Users/ash/miniconda3/envs/py35/lib/python3.5/site-packages/giraffez/core.py", line 80, in run
    args.run(args)
  File "/Users/ash/miniconda3/envs/py35/lib/python3.5/site-packages/giraffez/commandline.py", line 243, in run
    for i, row in enumerate(exportfn(), 1):
  File "/Users/ash/miniconda3/envs/py35/lib/python3.5/site-packages/giraffez/export.py", line 256, in _fetchall
    data = self.export.get_buffer()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 376: invalid start byte
```

The typical way I connect to our Teradata instance using a SQL editor like DBeaver, the JDBC connection string has charset=UTF8 and my ODBC settings are also set that way in odbc.ini file. When I do `sys.getdefaultencoding()` I am also getting 'utf-8'.

**Comment by ausiddiqui** [comment]
On further investigation it always fails on fields that are DATETIME, if I cast those fields as VARCHAR or CHAR this issue does not arise. Is there a graceful way of dealing with TD datetime / timestamp objects and handling the conversion to Python?

**Comment by ChrisRx** [comment]
I apologize, I completely missed your issue until now.

Python is pretty bad about indicating what it might be when serialization/encoding are involved, and in this case it seems like it is most likely not a Unicode related problem, but rather something about the data it is getting back.  However, to test and make sure can you output the same command to a file instead of stdout?  I just want to eliminate the case where the term unicode support would somehow be affecting it (however unlikely given the traceback).

This seems like it might be something else related to the DATETIME type itself that might be wrong.  Could you also run the same query above and add `-vv` to get a full breakdown of the columns with it?  The message seems to indicate something that may be incorrectly handling the DATETIME type.

Also, just as a note, giraffez doesn't make use of any ODBC libraries or configuration so you shouldn't have to set anything in there.

If you can paste in the requested information that will be incredibly helpful.  Right now my theory is that this is just a DATETIME size that is non-normal or unexpected and the C code that is parsing the Teradata types is doing so incorrectly.  Another interesting thing is that macOS has some weird edges around how it handles some C types so that might also be in play here as well.

**Comment by ausiddiqui** [comment]
Hi Chris,

Thanks for getting back. I used the `-vv` command, but seems like no additional information is provided.

```bash
myComp:~|⇒  giraffez export "select top 100 * from mydb.fiscalDates" -vv
3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
Connection: Connecting to data source 'data-server' ...
Connection: Connection to 'data-server' established successfully.
Debug[2]: Statement (sanitized): Statement(columns=0, rows=0, executed=False, error=None)
Export: Initiating Teradata PT request (awaiting server)  ...
Export: Teradata PT request accepted.
Export: Executing ...
  delimiter => "|"
  null      => "NULL"
  output    => "stdout"
  encoding  => "str"
  query     => "select top 100 dtGMT, fiscalYear, fiscalQuarter, fiscalWeek from mydb.fiscalDates"
--------------------------------
dtgmt|fiscalyear|fiscalquarter|fiscalweek
Connection: Closing Teradata connection ...
Export: Closing Teradata PT connection ...
Export: Teradata PT request complete.
Connection: Connection to 'data-server' closed.
Traceback (most recent call last):
  File "/Users/ash/miniconda3/envs/py35/bin/giraffez", line 11, in <module>
    sys.exit(main())
  File "/Users/ash/miniconda3/envs/py35/lib/python3.5/site-packages/giraffez/__main__.py", line 25, in main
    MainCommand().run()
  File "/Users/ash/miniconda3/envs/py35/lib/python3.5/site-packages/giraffez/core.py", line 80, in run
    args.run(args)
  File "/Users/ash/miniconda3/envs/py35/lib/python3.5/site-packages/giraffez/commandline.py", line 243, in run
    for i, row in enumerate(exportfn(), 1):
  File "/Users/ash/miniconda3/envs/py35/lib/python3.5/site-packages/giraffez/export.py", line 256, in _fetchall
    data = self.export.get_buffer()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 197: invalid start byte
```

If I change my query to:
```sql
select top 100 cast(dtGMT as varchar(10)) as dt, fiscalYear, fiscalQuarter, fiscalWeek from mydb.fiscalDates
```
I get the following:

```bash
dtgmt|fiscalyear|fiscalquarter|fiscalweek
12/09/15|2012|4|51
11/09/08|2011|4|50
16/06/20|2016|3|39
18/12/14|2019|1|11
05/03/16|2005|2|25
```
Within Teradata the field `dtgmt` has values that are displayed as '2015-09-12' and is DATETIME field type.

**Comment by ChrisRx** [comment]
Could you re-run the query with `-vv` and use `cmd` instead of `export`?  I think the export command is not spitting out the full column info which is what I think would be helpful here in solving this issue.  My theory is still that on macOS the datetime field size is different than on Linux and Windows.  Hopefully if you re-run the command using `giraffez cmd ...` instead it will print out the data type information for the columns (which includes the length in bytes).

**Comment by ChrisRx** [comment]
I believe I have addressed the problem.  The default date form is generally the Teradata format (date stored as an integer), but I think in your case the Teradata server has a default of ANSI date (the 10 character string ISO date).  The Teradata CLIv2 documentation indicates that Teradata format is always available, while ANSI is not necessarily supported on all systems (although my guess is that it probably will be available on almost all systems).  With that in mind, I'm explicitly setting the date form to be used to Teradata, which will override the default ANSI date and return the date that is already expected by giraffez.  Let me know if this doesn't work for you, but I'm confident it should (just reopen the issue and I will take another look).

Thanks for your patience and help!

**Comment by EWingate7** [comment]
Fantastic!! We'll test it out. Thanks @ChrisRx

**Comment by ChrisRx** [comment]
I put the sdist and a macos wheel up on PyPi just now.  I will be able to put the Windows wheels on there this evening if you are in need of those.

**Comment by ausiddiqui** [comment]
This is working perfectly, my original issue is fully resolved! Thank you so much!

**Comment by EWingate7** [comment]
Agreed, its working for me as well. Thank you!!
