### ISSUE TITLE
TeradataError: 3130: Response limit exceeded with cmd.insert

### ISSUE THREAD

**Issue by skunkwerk** [capitalone/giraffez#51]
When I try to insert ~1 million rows using the following syntax:

with giraffez.Cmd(panic=True) as cmd:
    cmd.insert('db.table_name', 'data.csv')

it runs for about a minute and inserts ~8,000 rows of data, and then stops with the following error:
giraffez.TeradataError: 3130: Response limit exceeded.

I believe this is caused by not closing the responses from Teradata (max allowed to keep open is 16):
https://stackoverflow.com/questions/18903284/teradata-database-3130-response-limit-exceeded

thank you

**Comment by ChrisRx** [comment]
The first thing I wanted to mention is to consider using the mload protocol instead of multi-statement inserts (`giraffez.BulkLoad`) since it has a much lower negative affect on the database and is (generally) much faster, when dealing with rows in the millions (like I said, generally, there are certainly edge cases with that one but still worth mentioning).

The `insert` method is synchronous and uses only one connection.  Because giraffez sets the KeepResp connection flag to be `N` (seen being set [here](https://github.com/capitalone/giraffez/blob/master/giraffez/src/teradata.c#L73)), it means that this one connection will **not** keep the response open until explicitly closed or exhausted (it will release as soon as the connection is released at the end of the context), and it being synchronous in nature will only produce one possible resp at at time towards the 16 limit.  This makes me think potentially something else is happening, either other sessions from something else, or possibly something weird with how some of the platform specific libraries behave.  What platform/architecture (Windows, macOS, linux, etc), what version of giraffez, and what version of Python?



Since quite a few

**Comment by ChrisRx** [comment]
Closing due to lack of response.
