### ISSUE TITLE
What is the advantage of CLIv2 vs JDBC and ODBC?

### ISSUE THREAD

**Issue by dclong** [capitalone/giraffez#59]
`giraffez` is using CLIv2 which I have no knowledge in. I'm curious that what is the advantage of CLIv2 vs JDBC and ODBC?

**Comment by ChrisRx** [comment]
In short, the [CLIv2/TPTAPI](https://capitalone.github.io/giraffez/FAQ.html#what-are-the-teradata-call-level-interface-version-2-and-teradata-parallel-transporter-api-and-how-do-i-get-them) are official Teradata C/C++ libraries for interacting with Teradata server.  There are some nuance but that is mostly the reason these were used.

The CLIv2, TPTAPI, JDBC, and ODBC are all various methods for interfacing with Teradata server.  They all differ greatly in capability and implementation.  The most straightforward is ODBC, which uses the common ODBC API for which Teradata implements to some degree.  The CLIv2, however, is the official low-level call library for which almost all client capabilities are derived (written in C).  For example, ODBC in some manner is most likely implemented (on the server-side) with some (or a lot of) interaction with the CLIv2.  Giraffez chose this as its library so that it could have the most powerful interface to Teradata that is provided (in performance and capability).  Teradata has implemented bulk loading procedures (fastload, multiload, etc) in C++, using the CLIv2 at its core and is where the TPTAPI comes in (Teradata Parallel Transporter API).  Giraffez uses this to perform bulk load procedures not available to ODBC or naively via CLIv2.

JDBC ends up being a mix (functionally) of both ODBC and Teradata has chosen to re-implement the bulk protocols purely in Java.  Ultimately what this means is that the JDBC is capable of doing "normal" SQL interactions with Teradata, while also being able to do bulk protocols like fastload/multiload or fastexport.

Giraffez uses the CLIv2 and the TPTAPI, under the hood, specifically to provide the greatest surface area for interacting with Teradata possible.  The advantages, for instance, over ODBC is that ODBC does not allow for usage of the bulk protocols.  The other advantages are being able to bind C/C++ with Python code vs. something like translating Java types to Python types with the JDBC.

**Comment by dclong** [comment]
@ChrisRx Thank you so much for the detailed explanation! This is very help!

I asked the same the question on Stack Overflow. Mind to copy and paste your answer there? This should be the accepted answer!
https://stackoverflow.com/questions/52016778/advantage-of-teradata-cliv2-vs-jdbc-and-odbc

**Comment by ChrisRx** [comment]
Sure, I do not mind.  I'm glad it helped!
