### ISSUE TITLE
Version Release?

### ISSUE THREAD

**Issue by jredd** [capitalone/giraffez#7]
Is this a stable release? If so why isn't there a release version in the releases section?

**Comment by ktravis** [comment]
We are managing releases in PyPI, which is the preferred method of installing giraffez given that building the extensions from source (rather than installing the distributed wheels via pip) takes varying degrees of environment setup depending on platform. The intent is that "work in progress" is not committed to the master branch, so in that sense it is intentionally stable. 

Regarding API stability, we are following semantic versioning with giraffez. At the point of another major release in the future we may utilize tagging/GitHub releases to better delineate version changes -- at the moment it did not seem particularly useful to provide "releases" via GitHub, which would essentially be a snapshot of the project source from a particular commit. If there is a desire for that outside of PyPI, I would be open to it, but I haven't thought of the motivation for it yet. If you are using giraffez we highly recommend keeping current with the latest release, as the majority of patch/minor version increments are bugfixes and performance enhancements. Locking a particular version is easily accomplished via pip, but if another facility for doing so is needed I wouldn't rule out the possibility.

Hopefully this answers your question, please let me know if I can clarify anything else!

**Comment by jredd** [comment]
Ah fair enough. I was just curious. When I look at a potential repo to use I look at the contributions to the repo and the release version as well as being on PyPi. It helps me determine longevity and support for a repo and if it's healthy. I don't know if other developers do what I do when determining if it's worth integrating a module into their project or not but it's just something I do.

**Comment by ktravis** [comment]
That's a good point. Since this was originally an internal Capital One project, to avoid confusion and any other associated issues we did not include commit history or past versions in the external release, and additionally reset the project version to 1.0.0 to correspond with the public launch.

Thank you for your interest!
